version: "3.7"

services:
  web:
    container_name: "web"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
      labels:
        - "django_project_3_bookstore"

    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn project_3_bookstore.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

    networks:
      - django_postgresql

  db:
    container_name: db
    image: postgres:11
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django_postgresql

volumes:
  postgres_data:

networks:
  django_postgresql:
